var Labels = {
    ProductSearchText: "Search Your product..",
    AppName: "E-Cart",
    productNameAndDetails :"Lorem ipsum dolor sit amet, et paulo ceteros eligendi sea, et mel velit saepe voluptua. Viris sanctus propriae ex mel, atqui senserit sea an. Eu diam vidisse sed. Nam zril essent dictas at, an duo graece invenire omittantur.",
    fullDescription :"Lorem ipsum dolor sit amet, et paulo ceteros eligendi sea, et mel velit saepe voluptua. Viris sanctus propriae ex mel, atqui senserit sea an. Eu diam vidisse sed. Nam zril essent dictas at, an duo graece invan duo graece invenire omittantur. Lorem ipsum dolor sit amet, et paulo ceteros eligendi sea, et mel velit saepe voluptua. Viris sanctus propriae ex mel, atqui senserit sea an. Eu diam vidisse sed. Nam zril essent dictas at, an duo graece invenire omittantur. Lorem ipsum dolor sit amet, et paulo ceteros eligendi sea, et mel velit saepe volupt ttantur. Lorem ipsum dolor sit amet, et paulo ceteros eligendi sea, et mel velit saepe voluptua. Viris sanctus propriae ex mel, atqui senserit sea an. Eu diam vidisse sed. Nam zril essent dictas at, an duo graece invenire omittantur. Lorem ipsum dolor sit amet, et paulo ceteros eligendi sea, et mel velit saepe volupt ua. Viris sanctus propriae ex mel, atqui senserit sea an. Eu diam vidisse sed. Nam zril essent dictas at, an duo graece invenire omittantur. Lorem ipsum dolor sit amet, et paulo ceteros eligendi sea, et mel velit saepe voluptua. Viris sanctus propriae ex mel, atqui senserit sea an. Eu diam vidisse sed. Nam zril essent dictas at, an duo graece invenire omittantur. Lorem ipsum dolor sit amet, et paulo ceteros eligendi sea, et mel velit saepe voluptua. Viris sanctus propriae ex mel, atqui senserit sea an. Eu diam vidisse sed. Nam zril essent dictas at, an duo graece invenire omittantur. Lorem ipsum dolor sit amet, et paulo ceteros eligendi sea, et mel velit saepe voluptua. Viris sanctus propriae ex mel, atqui senserit sea an. Eu diam vidisse sed. Nam zril essent dictas at, an duo graece invenire omittantur.",
    Remove:"Remove",
    PriceDetails:"Price Details",
    CartTotal:"Cart Total",
    CartDiscount:"Cart Discount",
    TotalAmount:"Total Amount",
    TotalAmountPayable:"Total Amount Payable",
    YouSave:"* You Save ",
    CheckOut:"Check Out",
    description:"Description",
    addToCard:"ADD TO CART",
    removeCard:"REMOVE CART",
    deliveryAddress:"Delivery Address",
    sampleName:"Sri ganesh",
    sampleAddress:"2/179, Dhasampalayam. mettupalayam, coimbatore tamilnadu 641-305",
    mobileNo:"Mobile Number : ",
    samplemobileNo:"8344233713",
    subAmount:"Sub Total",
    deliveryCharge:"Delivery Charge",
    paymentMethod:"Payment Method",
    details:"Details",
    orderPlaced:"Order Placed",
    total:"Total",
    status:"Status",
    cancel:"CANCEL",
    track:"TRACK",
    shippingInfo:"Shipping Info",
    quantity:"Quantity: ",
    sellingPrice:"Selling Price: ",
    yourOrders:"Your Orders",
    back:"Back",
    orderDetails:"Order Details",
    orderStatus:"Order Status",
    SavedAddress:"Saved Address",
    addNewAddress:"Address",
    addressEmpty:"Saved Address is Empty",
    addressEmptyNotes1:"Looks like you haven't saved any",
    addressEmptyNotes2:"delivery address yet",
}

export default Labels